version: '3.8'
services:
  n8n:
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n-network
    ports:
      - "5678:5678"

networks:
  n8n-network:
    name: n8n-network

volumes:
  n8n_data:
    name: n8n_data
